name: Deploy to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_REGION: "East US"  # Try this region instead

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_DEBUG: 'False'
    
    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r applications accounts catalog core manage.py requirements.txt deploy/
        if [ -d "staticfiles" ]; then cp -r staticfiles deploy/; fi
        cd deploy && zip -r ../career-campass-deploy.zip .
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'career-compass'
        resource-group-name: 'career-compass-group'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./career-campass-deploy.zip
    
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create resources in allowed region
    - name: Create Azure Resources
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Creating resource group if it doesn't exist..."
          az group create --name career-compass-group --location "${{ env.AZURE_REGION }}" --only-show-errors || echo "Resource group exists or couldn't be created in this region"
          
          echo "Creating app service plan..."
          az appservice plan create --name ASP-careercompass \
            --resource-group career-compass-group \
            --sku B1 \
            --location "${{ env.AZURE_REGION }}" \
            --is-linux \
            --only-show-errors || echo "App service plan exists or couldn't be created in this region"
            
          echo "Creating web app if it doesn't exist..."
          az webapp create --name career-compass \
            --resource-group career-compass-group \
            --plan ASP-careercompass \
            --runtime "PYTHON:3.13" \
            --only-show-errors || echo "Web app exists or couldn't be created in this region"
    
    - name: Configure App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name career-compass --resource-group career-compass-group \
          --settings \
          DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
          DJANGO_DEBUG="False" \
          DJANGO_ALLOWED_HOSTS="career-compass.azurewebsites.net,localhost,127.0.0.1" \
          DJANGO_SETTINGS_MODULE="core.settings"
